apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-deployment
  labels:
    app: quotes-app-deployment
spec:  
  replicas: 3
  selector:
    matchLabels:
      app: quotes-pod
  template:
    metadata:
      labels:
        app: quotes-pod
    spec:
      containers:
      - name: quotes-container
        image: magnuslarsson/quotes:go-22
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: quotes-service-np
spec:
  type: NodePort
  selector:
    app: quotes-pod
  ports:
    - port: 8080
      nodePort: 31000
