apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-app-deploy
  labels:
    app: quotes-app-lb-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: quotes-app-lb-pod
  template:
    metadata:
      labels:
        app: quotes-app-lb-pod
    spec:
      containers:
      - name: quotes-app-container
        image: magnuslarsson/quotes:go-22
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: quotes-service-lb
spec:
  type: LoadBalancer
  selector:
    app: quotes-app-lb-pod
  ports:
    - port: 8080  
      nodePort: 32000
