apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: guestbook-pod
      tier: frontend-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: guestbook-pod
        tier: frontend-pod
    spec:
      containers:
      - name: php-app-container
        image: pbadhe34/my-apps:php-redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # In case of 'dns' the host name lookup is 'redis-master' for cmd=set
          # In case of "DNS" mappoing the value looked upon is 'redis-slave' for cmd =
          ## get 
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          #value: env
          #In case of 'env' value the host name look up in  guestbook.php  is
           # ' REDIS_MASTER_SERVICE_HOST' or 'REDIS_SLAVE_SERVICE_HOST' anbd addd as
          ## environmnet vlaue in the pods
        ports:
        - containerPort: 8090
