apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave-deployment
spec:
  selector:
    matchLabels:
      app: redis-pod
      role: slave-pod
      tier: backend-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-pod
        role: slave-pod
        tier: backend-pod
    spec:
      containers:
      - name: slave-container
        image: gcr.io/google_samples/gb-redisslave:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          #value: dns
          ##n case of 'dns' the host name lookup is 'redis-master'  with value as ip
          ## address of redis-master host
          # If your cluster config does not include a dns service, then to
          # instead access an environment variable to find the master
          # service's host, comment out the 'value: dns' line above, and
          # uncomment the line below:
          value: env
          # In case of 'env' value the host name look up in  is
          # ' REDIS_MASTER_SERVICE_HOST' and added as env variable with value as ip
          ## address of address of redis-master host
        ports:
        - containerPort: 6379
