apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis-slave-app
    role: slave-role
    tier: backend-service
spec:
  ports:
  - port: 6379
  selector:
    app: redis-pod
    role: slave-pod
    tier: backend-pod
