apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-backend
  template:
    metadata:
      labels:
        app: azure-vote-backend
    spec:
      containers:
      - name: azure-redis-container
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
 name: azure-vote-back-service
spec:
 ports:
  - port: 6379
 selector:
    app: azure-vote-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-pod
  template:
    metadata:
      labels:
        app: azure-vote-pod
    spec:
      containers:
      - name: azure-vote-app-container
        image: microsoft/azure-vote-front:redis-v1
        ports:
        - containerPort: 80          
        env:
        - name: REDIS  #THE NAME OF REDIS SERVICE HOST
          value: "azure-vote-back-service"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote-pod
